torchbox/rca-wagtail-2019

rca/project_styleguide/templates/patterns/atoms/link-tertiary/link-tertiary.html
rca/project_styleguide/templates/patterns/atoms/pathway-item/pathway-item.html
rca/project_styleguide/templates/patterns/atoms/pathway-item/pathway-item.yaml
rca/project_styleguide/templates/patterns/molecules/cookie-message/cookie-message.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
rca/project_styleguide/templates/patterns/molecules/pathways/pathways.html
rca/project_styleguide/templates/patterns/molecules/pathways/pathways.yaml
rca/project_styleguide/templates/patterns/pages/programme-detail/programme-detail.html
rca/static_src/sass/base/_typography.scss
rca/static_src/sass/components/_introduction.scss
rca/static_src/sass/components/_key-details.scss
rca/static_src/sass/components/_link.scss
rca/static_src/sass/components/_pathway-item.scss
rca/static_src/sass/components/_pathways.scss
rca/static_src/sass/components/_programme-overview.scss
rca/static_src/sass/components/_section.scss
rca/static_src/sass/layout/_header.scss
rca/static_src/sass/main.scss

Key details, programme intro, pathways and sorting out global line height in one MR (sorry)

Programme detail page components

---

rca/static_src/javascript/components/slideshow.js

Ensure resize isn’t fired if window same size

---

rca/project_styleguide/templates/patterns/organisms/contact/contact.html
rca/project_styleguide/templates/patterns/organisms/contact/contact.yaml
rca/project_styleguide/templates/patterns/pages/programmes/programme_detail.html
rca/static_src/sass/components/_contact.scss
rca/static_src/sass/main.scss

For https://projects.torchbox.com/projects/rca-website-rebuild/tickets/63

Contact section

---

rca/settings/base.py

- ref https://github.com/django/channels/issues/871#issuecomment-373486712

Remove due to too many connections error in sentry

---

rca/project_styleguide/templates/patterns/organisms/programme_tabs/programme_overview.html

rich-text class for programme-overview description

---

requirements-dev.txt

https://nvd.nist.gov/vuln/detail/CVE-2019-14806

Update werkzeug in dev requirements

---

rca/project_styleguide/templates/patterns/organisms/facilities/facilities.html
rca/project_styleguide/templates/patterns/organisms/slideshow/slideshow.html

[Ticket 178](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/178)

178 gallery arrows

---

rca/programmes/models.py
rca/project_styleguide/templates/patterns/pages/programmes/programme_index.html

Renders out taxonomy values to the template as json

Render out taxonomy items to json for react filters

---

rca/project_styleguide/templates/patterns/atoms/sprites/sprites.html
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.js
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.scss
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.test.js
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesTablist.js
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesTablist.scss
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoryItem.js
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoryItem.scss
rca/static_src/javascript/programmes/components/ProgrammesCategories/ProgrammesCategories.js
rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.js
rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.scss
rca/static_src/sass/abstracts/_variables.scss
rca/static_src/sass/components/_contact.scss
rca/static_src/sass/components/_image.scss
rca/static_src/sass/components/_section.scss
rca/static_src/sass/main.scss

See https://projects.torchbox.com/projects/rca-website-rebuild/tickets/253.
Design: https://www.figma.com/file/EWOmjORgGoHnfba7OSGmQ3ic/RCA---Phase-1-Shared?node-id=1810%3A2
---
The categories do not match what is described on the ticket and in the designs but otherwise this works the same. Ordering of the items is also to be done separately.

#253 Programme category views

---

rca/static_src/javascript/programmes/components/ProgrammesCategories/ProgrammesCategories.js
rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
rca/static_src/javascript/programmes/components/ProgrammesExplorer.scss
rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.js
rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.scss
rca/static_src/javascript/programmes/components/SearchForm.js
rca/static_src/javascript/programmes/programmes.routes.js
rca/static_src/javascript/programmes/programmes.slice.js
rca/static_src/sass/main.scss

See https://projects.torchbox.com/projects/rca-website-rebuild/tickets/252.
This MR focuses on:
- Adding (minimal) transitions between the different views of the programmes listing
- Saving the user’s search query in the browser URL

#252 Programme index view transitions & URL state

---

rca/project_styleguide/templates/patterns/atoms/profile-image/profile-image.html
rca/project_styleguide/templates/patterns/molecules/job-titles/job-titles.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--staff.html
rca/static_src/sass/components/_profile-image.scss

Based on `feature/short-course-ALL-FE` - with additional of staff detail template and components

[WIP] Feature/staff detail FE

---

.circleci/config.yml

CI Updates to use TBX's new deployment setup

423 - Circle CI changes to the new deployment config

---

rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/438

[438] Landing page breadcrumbs

---

rca/project_styleguide/templates/patterns/molecules/no-results/no-results.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/402

[402] Project picker no results button text

---

rca/project_styleguide/templates/patterns/pages/project/project_listing.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/400#update-63182359

[400] Hide meta title from featured listing on project listing page 

---

rca/static_src/sass/components/_card.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/440

fix items in carousel with short teaser copy

---

rca/static_src/sass/abstracts/_variables.scss
rca/static_src/sass/components/_app.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/458

[458] Anchor nav above footer

---

rca/project_styleguide/templates/patterns/atoms/reset/reset.html
rca/project_styleguide/templates/patterns/molecules/no-results/no-results.html
rca/project_styleguide/templates/patterns/pages/project/project_listing.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/400

[400] Project page title and reset button text

---

rca/project_styleguide/templates/patterns/pages/staff/staff_listing.html
rca/project_styleguide/templates/patterns/pages/staff/staff_listing.yaml

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/463

[463] Person listing hero

---

rca/project_styleguide/templates/patterns/molecules/anchor-nav/anchor-nav.html
rca/project_styleguide/templates/patterns/pages/guide/guide.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/462

[462] Add contact to in page nav 

---

rca/project_styleguide/templates/patterns/pages/guide/guide.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/462#update-63391827

[462] Solo contact link in menu

---

rca/project_styleguide/templates/patterns/molecules/card/card--staff.html
rca/project_styleguide/templates/patterns/molecules/card/card--staff.yaml
rca/project_styleguide/templates/patterns/pages/staff/staff_listing.html
rca/project_styleguide/templates/patterns/pages/staff/staff_listing.yaml
rca/static_src/sass/components/_card.scss

Dependent on https://github.com/torchbox/rca-wagtail-2019/pull/420 which should be merged first.
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/464

[464] Person listing results

---

rca/static_src/javascript/components/project-filters.js
rca/static_src/sass/components/_filter-bar.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/474

[474] Project page mobile filters active state

---

rca/static_src/sass/components/_title-area.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/446

[446] Breadcrumb/Title visibility 

---

rca/project_styleguide/templates/patterns/molecules/navigation/primarynav.html
rca/static_src/javascript/components/back-link.js
rca/static_src/javascript/components/submenu.js
rca/static_src/sass/base/_base.scss
rca/static_src/sass/components/_back-link.scss
rca/static_src/sass/components/_nav.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/467

[467] Mobile menu updates

---

rca/project_styleguide/templates/patterns/pages/project/project_listing.html
rca/project_styleguide/templates/patterns/pages/staff/staff_listing.html
rca/static_src/javascript/components/project-filters.js
rca/static_src/javascript/components/tabs.js
rca/static_src/sass/components/_filter-tab-options.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/473

[473] Filters url updates

---

rca/static_src/javascript/components/project-filters.js
rca/static_src/sass/components/_page.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/475

[475] Project picker 'white bar' fix

---

rca/api_content/content.py
rca/people/admin/__init__.py
rca/people/admin/page_import.py
rca/people/admin/page_import_forms.py
rca/people/models.py
rca/people/templates/admin/import_export/page_import.html
rca/settings/base.py
requirements.txt

[Ticket](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/454)
Importing is handled in the Django admin using a custom `django-import-export` implementation.
Depends on #437 (to remove the required `job_title` field)

[454] Staff data migration (CSV import)

---

rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--dev-all-fields.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--dev-all-fields.yaml
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.yaml
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.yaml
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.yaml
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.yaml
rca/project_styleguide/templates/patterns/pages/researchcentre/research_centre.html
rca/project_styleguide/templates/patterns/pages/researchcentre/research_centre.yaml

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/485

[485] News/Events on landing and research centre pages

---

rca/static_src/javascript/components/modal.js

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/445

[445] Overlay link behaviour

---

rca/static_src/sass/components/_anchor-nav.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/468

[468] Anchor nav positioning

---

rca/project_styleguide/templates/patterns/molecules/anchor-nav/anchor-nav.html
rca/project_styleguide/templates/patterns/organisms/accordion-block/accordion-block.html
rca/project_styleguide/templates/patterns/organisms/contact/contact.html
rca/project_styleguide/templates/patterns/organisms/index-module/index-module.html
rca/project_styleguide/templates/patterns/organisms/people-module/people-module.html
rca/project_styleguide/templates/patterns/pages/guide/guide.html
rca/static_src/javascript/components/anchor-nav.js
rca/static_src/javascript/main.entry.js
rca/static_src/sass/components/_anchor-nav-item.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/460

[460] Active anchor nav

---

rca/project_styleguide/templates/patterns/base.html
rca/project_styleguide/templates/patterns/molecules/sitewide-alert/sitewide-alert.html
rca/project_styleguide/templates/patterns/molecules/sitewide-alert/sitewide-alert.yaml
rca/static_src/javascript/components/sitewide-alert.js
rca/static_src/javascript/main.entry.js
rca/static_src/sass/components/_sitewide-alert.scss
rca/static_src/sass/main.scss

[Codebase ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1069)

[1069] Site-wide overlay alert message (FE)

---

rca/project_styleguide/templates/patterns/molecules/streamfield/blocks/image_block.html
rca/project_styleguide/templates/patterns/molecules/streamfield/stream_block.html
rca/project_styleguide/templates/patterns/pages/guide/guide.html

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/521

[521] Guide page image size

---

rca/project_styleguide/templates/patterns/atoms/modal-launcher/modal-launcher.html
rca/project_styleguide/templates/patterns/base.html
rca/project_styleguide/templates/patterns/molecules/booking-bar/booking-bar.html
rca/project_styleguide/templates/patterns/molecules/breadcrumb/breadcrumb.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
rca/project_styleguide/templates/patterns/molecules/navigation/primarynav.html
rca/project_styleguide/templates/patterns/molecules/profile-detail/profile-detail.html
rca/project_styleguide/templates/patterns/molecules/slide/slide.html
rca/project_styleguide/templates/patterns/organisms/carousel/carousel--quotes.html
rca/project_styleguide/templates/patterns/organisms/carousel/carousel--square.html
rca/project_styleguide/templates/patterns/organisms/carousel/carousel.html
rca/project_styleguide/templates/patterns/organisms/carousel/carousel_api_content.html
rca/project_styleguide/templates/patterns/organisms/image-video-block/image-video-block.html
rca/project_styleguide/templates/patterns/organisms/programme_tabs/programme_overview.html
rca/project_styleguide/templates/patterns/organisms/slideshow/slideshow.html
rca/project_styleguide/templates/patterns/pages/shortcourses/short_course.html
rca/static_src/sass/components/_skip-link.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/508

[508] Accessibility updates

---

rca/project_styleguide/templates/patterns/atoms/profile-teaser/profile-teaser.html

[Ticket 499](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/499)

Staff page not rendering on small profile teaser

---

rca/programmes/models.py
rca/project_styleguide/templates/patterns/molecules/relatedcontent/relatedprogrammes.html

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1105

1105 Allow publishers to choose guides and short courses here

---

rca/project_styleguide/templates/patterns/molecules/profile-detail/profile-detail.html

Ticket https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1099

Missing staff.title value

---

rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html

Ticket https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1081

Switch to render the document object title here

---

.circleci/config.yml
rca/settings/base.py
requirements.txt

Add birdbath

---

rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
rca/project_styleguide/templates/patterns/pages/project/project_detail.html
rca/project_styleguide/templates/patterns/pages/researchcentre/research_centre.html
rca/project_styleguide/templates/patterns/pages/shortcourses/short_course.html
rca/static_src/sass/components/_title-area.scss

https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1093
Adds caption under hero image to following templates:
- Short course
- Research page
- Project detail
- Landing pages (enterprise, innovation and research)

[1093] Add hero image caption phase 2 templates

---

rca/static_src/sass/components/_pagination.scss

https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1098
Add active styles to pagination

[1098] Active pagination

---

rca/project_styleguide/templates/patterns/organisms/footer/footer.html

For [ticket 1102](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1102)

Remove trademark notice from site footer

---

rca/static_src/sass/components/_nav.scss
rca/static_src/sass/layout/_header.scss

Ensures main menu on desktop can scroll when viewed on short screens. 
Also tweaks the gradient so that works consistently in all browsers.
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1110

[1110] Desktop menu scroll

---

rca/people/models.py

For [ticket 1092](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1092)

Add automated listing of research projects to staff page

---

rca/static_src/sass/components/_anchor-nav-item.scss

Pushed to staging here:
https://rca-staging.herokuapp.com/pattern-library/render-pattern/patterns/pages/guide/guide.html

Fix for anchor nav item active links

---

.pre-commit-config.yaml
rca/research/models.py

Ticket [644](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/644#update-65811153)

Stop showing draft courses and programmes

---

.sass-lint.yml
rca/project_styleguide/templates/patterns/molecules/job-titles/job-titles.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--student.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--student.yaml
rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html
rca/project_styleguide/templates/patterns/pages/student/student_detail.html
rca/project_styleguide/templates/patterns/pages/student/student_detail.yaml
rca/static_src/sass/components/_staff-body.scss

Contains:
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/654
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/633
Based on the staff profile page that we already have

Student profile FE

---

.pre-commit-config.yaml
rca/forms/models.py

Ticket [651](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/651)
Small change to enable Wagtail forms

651 enable wagtail forms

---

.isort.cfg
rca/project_styleguide/templates/patterns/pages/schools/schools.html
rca/schools/factories.py
rca/schools/models.py
rca/schools/tests/test_models.py
requirements.txt

Addresses feedback on [606](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/606#update-65991341)

606 Correct links to prefiltered listings

---

rca/images/models.py
rca/project_styleguide/templates/patterns/base_page.html

see https://github.com/wagtail/wagtail/issues/6803

Social image fix

---

rca/project_styleguide/templates/patterns/molecules/key-details/key-details--student.html
rca/project_styleguide/templates/patterns/pages/student/student_detail.html

Adding schema tags to the student profile template

Student detail SEO

---

rca/people/models.py

contains security updates and treebeard pin so the pipeline passes

1092 Ensure these pages are live before deciding to list them

---

rca/static_src/sass/layout/_header.scss

https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1153

Removing height from nav when search open

---

requirements.txt

Updates django for recent security fix for https://www.djangoproject.com/weblog/2021/feb/19/security-releases/

Security update

---

rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
rca/project_styleguide/templates/patterns/pages/shortcourses/short_course--no-dates.yaml
rca/shortcourses/models.py
rca/shortcourses/tests/test_models.py

https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1172

1172 - Amendments to hardcoded short course wording

---

rca/static_src/javascript/components/modal.js

Was causing issues when opening the modal for a second time

No longer wait for CSS on modal launch

---

rca/enquire_to_study/forms.py
rca/enquire_to_study/tests/test_forms.py
rca/enquire_to_study/views.py
rca/project_styleguide/templates/patterns/pages/enquire_to_study/enquire_form_page.html

This will need rebasing once #565 is in (it will fix tests)

622 Fixes to initial values

---

rca/enquire_to_study/wagtail_hooks.py

Rounds up feedback on https://projects.torchbox.com/projects/rca-website-rebuild/tickets/682

Updates to listing filters

---

rca/project_styleguide/templates/patterns/pages/forms/form_page_landing.html

Part of https://projects.torchbox.com/projects/rca-website-rebuild/tickets/681
In terms of Pull Requests, [681](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/681) is going to be split out so we aren't depending on the enquire to study form work.

#681 Add tracking to form page landing

---

rca/static_src/sass/components/_link.scss
rca/static_src/sass/components/_rich-text.scss

https://projects.torchbox.com/projects/rca-website-rebuild/tickets/741

All .links to show underline when within form-items

---

rca/enquire_to_study/forms.py
rca/project_styleguide/templates/patterns/pages/enquire_to_study/enquire_form_thanks.html

Implements changes for [622](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/622#update-66831401)

622 General form updates and changes

---

rca/api_content/content.py

https://sentry.io/organizations/torchbox/issues/2341795466/?environment=production&project=1542908&query=is%3Aunresolved

Fix variable referenced before assignment error

---

docs/mailchimp-integration.md
mkdocs.yml

Added documentation to help other developers working on mailchimp work
Related to ticket [623](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/623)

623 mailchimp documentation

---

rca/enquire_to_study/factories.py
rca/enquire_to_study/templates/enquire_to_study/confirm_delete.html
rca/enquire_to_study/tests/test_views.py
rca/enquire_to_study/views.py

Ticket: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/732
Adds new date filters to only delete submissions older than 7 days, as well as updating the template text and new UI state where their are submissions but no submissions over 7 days to delete (will confirm the text for that one with Frank).

732 Enquiry Form Amend delete submissions

---

rca/enquire_to_study/views.py
rca/project_styleguide/templates/patterns/pages/enquire_to_study/enquire_form_thanks.html
rca/project_styleguide/templates/patterns/pages/forms/thanks.html

Part 2 of https://projects.torchbox.com/projects/rca-website-rebuild/tickets/681
For the custom enquiry form, we need to ensure the form submission is sent to analytics.

#681 enquiry form tracking

---

rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details.yaml

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1204
Preview of page in pattern library:
Preview of live data:

[204] Add school to programme page (FE)

---

rca/static_src/sass/components/_video-modal.scss

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1281

[1281] Prevent tabbing to video modal when it's not open

---

rca/static_src/sass/components/_breadcrumb.scss
rca/static_src/sass/components/_video-modal.scss

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1207
Local preview:

[1207] Breadcrumb colour on mobile

---

rca/project_styleguide/templates/patterns/pages/schools/schools.html

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1205
Local preview:
Mobile:

[1205] 'Featured projects' title for schools page (FE)

---

rca/events/blocks.py
rca/events/models.py
rca/project_styleguide/templates/patterns/pages/events/event_detail.html
rca/project_styleguide/templates/patterns/pages/events/event_detail.yaml

Implements: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/882

[882] add event page partners carousel

---

rca/events/models.py
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--event.html
rca/project_styleguide/templates/patterns/pages/events/event_detail.yaml
rca/utils/wagtail_hooks.py

Implements: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/875
TODO: add migration when merged to event page feature branch

[875] add event type taxonomy

---

rca/landingpages/models.py
rca/project_styleguide/templates/patterns/pages/editorial_event_landing/editorial_event_landing.html

Wires up the jump menu for ticket [906](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/906)

Wires up the jump menu for the ee landing page

---

rca/project_styleguide/templates/patterns/molecules/key-details/key-details--alumni.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--alumni.yaml
rca/project_styleguide/templates/patterns/pages/alumni/alumni.html
rca/project_styleguide/templates/patterns/pages/alumni/alumni.yaml
rca/project_styleguide/templates/patterns/pages/guide/guide.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--dev-all-fields.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
rca/project_styleguide/templates/patterns/pages/schools/schools.html
rca/static_src/sass/base/_utility.scss
rca/static_src/sass/components/_introduction.scss
rca/static_src/sass/components/_link.scss
rca/static_src/sass/components/_project-overview.scss
rca/static_src/sass/components/_schools.scss
rca/static_src/sass/components/_section.scss
rca/static_src/sass/components/_text-teaser.scss

Alumni landing page as per design:
https://www.figma.com/file/XWY63bn8fmek4LbAtcxh2p/RCA-Phase-3-shared?node-id=5808%3A25152
Ticket:
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/824
Dev link:
https://rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/alumni/alumni.html

Alumni landing page FE

---

rca/events/models.py

Fixes https://sentry.io/organizations/torchbox/issues/2541744774/?environment=dev&project=1542908&query=is%3Aunresolved

[876] make event page booking fields required if booking bar shown

---

rca/project_styleguide/templates/patterns/base.html
rca/project_styleguide/templates/patterns/molecules/image-caption-link/image-caption-link.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--development.html
rca/project_styleguide/templates/patterns/molecules/key-details/key-details--development.yaml
rca/project_styleguide/templates/patterns/molecules/navigation/primarynav.html
rca/project_styleguide/templates/patterns/organisms/footer/footer.html
rca/project_styleguide/templates/patterns/pages/alumni/alumni.html
rca/project_styleguide/templates/patterns/pages/alumni/alumni.yaml
rca/project_styleguide/templates/patterns/pages/development/development.html
rca/project_styleguide/templates/patterns/pages/development/development.yaml
rca/static_src/sass/components/_card.scss
rca/static_src/sass/components/_image-caption-link.scss
rca/static_src/sass/layout/_header.scss

This PR adds the development template and styling
Ticket:
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/823
Designs:
https://www.figma.com/file/XWY63bn8fmek4LbAtcxh2p/RCA-Phase-3-shared?node-id=5717%3A23839
Development site:
https://rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/development/development.html

Development landing page fe

---

rca/landingpages/utils.py

Implements [925](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/925)

925 Update event teasers with location values now event code is merged

---

rca/landingpages/models.py

ticket [829](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/829)

829 Adds statistics to the alumni page

---

rca/landingpages/models.py

Ticket [934](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/934)

Wire up the in page nav

---

rca/landingpages/models.py

Ticket [837](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/837)

837 Exposes statistics field

---

rca/landingpages/models.py

Ticket [935](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/935)

935 Wire up the in page navigation items

---

rca/landingpages/models.py
rca/project_styleguide/templates/patterns/pages/development/development.html

Fixes for ticker [836](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/836#update-68030215)

Remove duplicate fields

---

rca/enquire_to_study/wagtail_hooks.py

Resolves sentry error https://sentry.io/organizations/torchbox/issues/2602131426/?environment=production&project=1542908&query=is%3Aunresolved

The types attribute has been removed, so this is causing errors when downloading

---

rca/project_styleguide/templates/patterns/organisms/programme_tabs/programme_overview.html
rca/project_styleguide/templates/patterns/pages/home/home_page.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--dev-all-fields.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html

https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1145

1145 - Amend hardcoded title of News & Events

---

rca/urls.py

Ticket: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/847
Wagtail MR used to help: https://git.torchbox.com/internal/wagtail-kit/-/merge_requests/647/diffs

847: Adding never_cache decorator to ensure private urls are not cached

---

rca/utils/models.py

Ticket [1003](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/1003)

Feature/1003 staff and content linking support 

---

README.md

Just to include how to trigger pipeline if deployment doesn't happen automatically.

Update deployment instructions on readme

---

rca/project_styleguide/templates/patterns/pages/scholarships/scholarship_form_thanks.html

Thanks template specific to the scholarships flow

Scholarships thanks template

---

rca/project_styleguide/templates/patterns/pages/scholarships/scholarships_listing_page.html
rca/scholarships/models.py

Fixes: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2374#update-68958513

[2374] add scholarships anchor link

---

rca/scholarships/factories.py
rca/scholarships/models.py
rca/scholarships/tests/test_models.py
rca/scholarships/wagtail_hooks.py

Implements: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2368

[2368] finish scholarship submission download

---

rca/scholarships/forms.py

Makes data protection policy field required and linked to policy

[2369] make scholarship privacy notice field required and linked

---

rca/static_src/javascript/components/scholarship-list.js
rca/static_src/javascript/main.entry.js

Javascript to output the JSON supplied by BE as a list of scholarships on the form page:
https://rca-development.herokuapp.com/scholarship-enquiry/

JS to output scholarships based on json

---

rca/project_styleguide/templates/patterns/pages/scholarships/scholarship_form_page.html
rca/scholarships/forms.py

Addresses: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2387#update-68983019
The eligibility choices are for FE testing only

[2387] scholarship form text tweaks

---

rca/urls.py

Changes scholarship form url: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2410

[2369] update scholarship form url

---

rca/scholarships/filters.py
rca/scholarships/models.py

don't show scholarships on listing on initial page load

[2377] don't show scholarships on listing on initial page load

---

rca/scholarships/forms.py
rca/scholarships/models.py
rca/scholarships/views.py

Implements: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2360

[2360] add sticky cta link and initial form filtering

---

rca/project_styleguide/templates/patterns/pages/project/project_detail.html
rca/project_styleguide/templates/patterns/pages/project/project_detail.yaml

Adding the logo carousel component to the project detail template
Ticket:
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2253
Dev:
https://rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/project/project_detail.html
Screenshots:

Adding logo carousel to project detail

---

rca/project_styleguide/templates/patterns/pages/project/project_listing.html
rca/static_src/sass/components/_image-video-block.scss

Adding a featured project title and moving the results heading
https://rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/project/project_listing.html
https://rca-development.herokuapp.com/research-innovation/projects/

Adding featured project and moving results title

---

rca/home/models.py

Resolves [#2432](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2432)

Fix news ordering and handling of None images

---

rca/static_src/sass/layout/_header.scss

Updating menu to 0.7 opacity - equivalent of https://colourcontrast.cc/000000/b3b3b3

Uping menu opacity to 0.7 for additional contrast

---

.circleci/config.yml
rca/project_styleguide/templates/patterns/pages/scholarships/scholarships_listing_page.html

Removes the booking bar component from the scholarship template.
Also includes fix for CI from Nick M's wagtail upgrade to ensure circleci can run.
Ticket: #2462

Removing booking bar from scholarship template

---

rca/enquire_to_study/views.py

Should resolve https://sentry.io/organizations/torchbox/issues/3729433117/?environment=production&project=1542908&query=is%3Aunresolved&referrer=issue-stream

BASE_URL  was missed in the upgrade

---

rca/project_styleguide/templates/patterns/molecules/navigation/standoutnav.html

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2472
This PR updates the URL value for the application portal link as it's hardcoded in a template and the publishers do not have the ability to change this themselves

#2472 Updates application portal URL value

---

rca/enquire_to_study/forms.py

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2470
This ticket updates the label, help text, and validation for the select programmes field.

#2470 - Enquire to study form: Programme field

---

rca/enquire_to_study/wagtail_hooks.py

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2467
This PR adds the city field to the exports. It also updates to show the full country name for shown for the country of residence.
Screenshot:

#2467 - BE: Enquire to study report - country and city of residence fields

---

rca/project_styleguide/templates/patterns/molecules/navigation/standoutnav.html
rca/project_styleguide/templates/patterns/molecules/steps/steps.html
rca/project_styleguide/templates/patterns/molecules/tab-nav/tab-nav.html
rca/project_styleguide/templates/patterns/organisms/contact/contact.html
rca/project_styleguide/templates/patterns/organisms/facilities/facilities.html
rca/project_styleguide/templates/patterns/organisms/image-video-block/image-video-block.html
rca/project_styleguide/templates/patterns/organisms/programme_tabs/curriculum.html
rca/project_styleguide/templates/patterns/organisms/programme_tabs/curriculum.yaml
rca/project_styleguide/templates/patterns/organisms/programme_tabs/fees-and-funding.html
rca/project_styleguide/templates/patterns/pages/home/home_page.html
rca/static_src/javascript/main.entry.js
rca/static_src/sass/components/_carousel.scss

Adding the testimonial component to the programmes curriculum tab
NEEDS BE before deploy
Ticket:
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/997
Staging:
https://rca-development.herokuapp.com//pattern-library/render-pattern/patterns/pages/programmes/programme_detail.html#curriculum

[WIP] Feature/997 add testi carousel to programmes

---

rca/project_styleguide/templates/patterns/molecules/search/search--inline.html
rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesTablist.js
rca/static_src/javascript/programmes/components/ProgrammesCategories/ProgrammesCategories.js
rca/static_src/javascript/programmes/components/SearchForm.js
rca/static_src/sass/components/_categories-tablist.scss
rca/static_src/sass/components/_search.scss
rca/static_src/sass/components/_section.scss

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2532
This pull request updates the search field for both the search page and the programme finder page. We will not be updating the one in the header.
Screenshots:

#2532 - FE - Increase Search Bar Prominence on programme finder and search results

---

rca/project_styleguide/templates/patterns/molecules/card/card.html
rca/project_styleguide/templates/patterns/organisms/staggered-cards/staggered-cards.html
rca/static_src/sass/components/_card.scss

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2534
This MR adds some icons to the link of the staggered card.
Testing instructions:
1. Pull data and visit the following link: `/study/application-process/`
Screenshot:

#2534 - FE | Staggered card module - Highlight Functionality of Links

---

rca/project_styleguide/templates/patterns/pages/donate/donate--pattern-library-only.html
rca/project_styleguide/templates/patterns/pages/donate/donate--pattern-library-only.yaml
rca/static_src/sass/components/_donate-form.scss

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2477
This merge request updates the styling to the donation form.
Testing instructions:
1. Visit the endpoint `/pattern-library/pattern/patterns/pages/donate/donate--pattern-library-only.html/` in the pattern library.
Screenshot:

#2477 - FE | Styling for Donation Form

---

rca/project_styleguide/templates/patterns/molecules/card/card.html
rca/project_styleguide/templates/patterns/molecules/relatedcontent/relatedcontent.html
rca/project_styleguide/templates/patterns/molecules/relatedcontent/relatedprogrammes--large.html
rca/project_styleguide/templates/patterns/molecules/relatedcontent/relatedprogrammes.html
rca/project_styleguide/templates/patterns/organisms/index-module/index-module.html
rca/static_src/sass/components/_card.scss
rca/static_src/sass/components/_related-content.scss

Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2533
This merge request adds the arrow to links in multiple places.
Screenshots:

#2533 - FE - Related Pages - Clearer Indication of Links

---

rca/static_src/sass/components/_rich-text.scss

Ticket: https://torchbox.monday.com/boards/1472452416/views/14036164/pulses/1509694722
Figma: https://www.figma.com/design/XWY63bn8fmek4LbAtcxh2p/RCA---Design-system?node-id=5867-0&t=X1DBoujC9NDQsvaP-1
<details><summary>Default</summary>
</details>
<details><summary>Hover/focus</summary>
</details>
<details><summary>Dark bg (accordion)</summary>
</details>
<details><summary>Dark bg hover/focus</summary>
</details>
<details><summary>Mobile</summary>
</details>

#4722 - Update rich text link style

---

rca/project_styleguide/templates/patterns/base.html
rca/utils/context_processors.py

As per recommendation on https://torchbox.monday.com/boards/1472452416/pulses/1538463496/posts/285731357

SEO: Add canonical tag to base template

---

rca/project_styleguide/templates/patterns/pages/events/event_detail.html

Ticket: https://torchbox.monday.com/boards/1472452416/views/14036164/pulses/1555021543

#1543: Fix schema.org markup for events

---

rca/static_src/sass/components/_table.scss

Addressing client feedback: https://torchbox.monday.com/boards/1472452416/pulses/1538457446/posts/315020938
- Remove table borders
- Align caption to the left

[7446] Typed table tweaks

---

rca/enquire_to_study/views.py
rca/events/forms.py
rca/landingpages/admin_forms.py
rca/people/models.py
rca/project_styleguide/templates/patterns/base.html
rca/project_styleguide/templates/patterns/base_page.html
rca/project_styleguide/templates/patterns/pages/editorial/editorial_listing.html
rca/project_styleguide/templates/patterns/pages/enquire_to_study/enquire_form_page.html
rca/project_styleguide/templates/patterns/pages/enquire_to_study/enquire_form_thanks.html
rca/project_styleguide/templates/patterns/pages/events/event_listing.html
rca/project_styleguide/templates/patterns/pages/home/home_page.html
rca/project_styleguide/templates/patterns/pages/project/project_listing.html
rca/project_styleguide/templates/patterns/pages/scholarships/scholarship_form_thanks.html
rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html
rca/project_styleguide/templates/patterns/pages/staff/staff_index.html
rca/project_styleguide/templates/patterns/pages/student/student_detail.html
rca/project_styleguide/templates/patterns/pages/student/student_index.html
rca/scholarships/views.py
rca/utils/forms.py
rca/utils/models.py
rca/utils/views.py

Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1588777159
Related ticket: https://torchbox.monday.com/boards/1472452416/pulses/1589345904

[7159] Make meta title and description fields required (and simplify templates)

---

rca/project_styleguide/templates/patterns/base.html
rca/utils/templatetags/util_tags.py

Ticket: https://torchbox.monday.com/boards/1472452416/views/14036164/pulses/1538463496

[3496] Add canonical tag to all pages

---

rca/enquire_to_study/wagtail_hooks.py
rca/scholarships/wagtail_hooks.py

Ticket: https://torchbox.monday.com/boards/1472452416/views/14036164/pulses/1598672601

[2601] Access to enquiry submissions shouldn't require full 'Admin' access

---

rca/project_styleguide/templates/patterns/pages/shortcourses/short_course.html
rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html

Incorrect template filter used was stopping links rendering in richtext areas

So links can render

---

rca/project_styleguide/templates/patterns/molecules/navigation/standoutnav.html

Updates hardcoded application portal content (in the main nav).
We'll make this a content-managed field in due course.

Update application portal link and label
