torchbox/rca-wagtail-2019

- rca/static_src/sass/components/_back-link.scss
hide the back button when searching but keep it's spacing so the search is in the correct place
> hide back button when search is open

- rca/settings/base.py
- rca/utils/clientip.py
So we always check against the real IP rather than X-Forwarded-For. This is so we can verify that requests went via the old site rather than direct.
> [119] Override basic auth get_client_ip function

- rca/project_styleguide/templates/patterns/molecules/navigation/standoutnav.html
have to be absolute urls due to proxying setup
> hardcoding standout nav links

- .isort.cfg
- rca/programmes/models.py
- rca/programmes/serializers.py
- rca/settings/base.py
- rca/urls.py
- rca/wagtailapi/api.py
- rca/wagtailapi/endpoints.py
- rca/wagtailapi/filters.py
#262, but against the right target branch 😐
---
Depends on #261. See https://projects.torchbox.com/projects/rca-website-rebuild/tickets/255.
This adds a basic implementation of Wagtail’s Pages API, with textual search and filtering by `degree_level`. There will be more filters needed but they should all follow a similar implementation (the fields aren’t there yet for the other filters).
> #255 Search results API

- rca/static_src/javascript/components/actual-height.js
- rca/static_src/javascript/main.js
- rca/static_src/sass/components/_hero.scss
When you have a sec could you give this a once over @chris-lawton ? Updating the hero area to be 100vh, on iOS and Mobile Chrome the menubars were overlapping the content previously.
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/177
> Fixing hero to be 100% height excluding any mobile nav bars

- rca/programmes/models.py
- rca/project_styleguide/templates/patterns/pages/programmes/programme_index.html
- rca/project_styleguide/templates/patterns/pages/programmes/programme_index.yaml
- rca/static_src/sass/components/_heading.scss
- rca/static_src/sass/components/_title-area.scss
See:
- Header: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/247
- Contact us: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/251
Design: https://www.figma.com/file/EWOmjORgGoHnfba7OSGmQ3ic/RCA---Phase-1-Shared?node-id=2099%3A55
The "Contact us" block is identical to the one on the programme details pages. The header wasn’t similar to other ones on the site so I created an "index" variation of `title-area`, which can hopefully be reused for other pages that have a hero-like heading without the full hero banner.
> #247, #251 programmes header, contact block

- rca/settings/base.py
Looks like we have the default set which means a new db connection per request.
ref: https://my.papertrailapp.com/systems/rca-production/events?focus=1151223290744188957&selected=1151223290744188957
> Don't use a new database connection for every request

- rca/project_styleguide/templates/patterns/atoms/sprites/sprites.html
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.js
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.scss
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.test.js
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesTablist.js
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesTablist.scss
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoryItem.js
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoryItem.scss
- rca/static_src/javascript/programmes/components/ProgrammesCategories/ProgrammesCategories.js
- rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
- rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.js
- rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.scss
- rca/static_src/javascript/programmes/components/SearchForm.js
- rca/static_src/javascript/programmes/programmes.routes.js
- rca/static_src/javascript/programmes/programmes.slice.js
- rca/static_src/sass/abstracts/_variables.scss
- rca/static_src/sass/components/_contact.scss
- rca/static_src/sass/components/_image.scss
- rca/static_src/sass/components/_section.scss
- rca/static_src/sass/main.scss
Depends on #278. There isn’t many changes here so this will be much easier to review once #278 is merged. See https://projects.torchbox.com/projects/rca-website-rebuild/tickets/250.
Design: https://www.figma.com/file/EWOmjORgGoHnfba7OSGmQ3ic/RCA---Phase-1-Shared?node-id=1810%3A2
---
This reuses the programmes’ search existing results view, with a light theme, to display results from categories.
There is still more work to be done for the transitions between those different views in a separate ticket.
> #250 Programmes filter by category results

- rca/programmes/models.py
- rca/project_styleguide/templates/patterns/pages/programmes/programme_index.html
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoryItem.js
- rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
- rca/static_src/javascript/programmes/programmes.routes.js
- rca/static_src/javascript/programmes/programmes.types.js
See https://projects.torchbox.com/projects/rca-website-rebuild/tickets/262. I did most of the small styles changes directly on `feature/programmes-listing`, but wouldn’t mind feedback on a few bigger pieces:
- Adding a canonical to the page – not part of the feedback but I noticed I forgot to add it.
- Adding the slugs in the URL, based on the new fields from @kevinhowbrook. This was easier than I thought!
- Reordering and renaming the categories. This was marked as "Post-launch", but is very little work so might as well do it at the same time.
> #262 Changes based on programmes listing feedback

- .isort.cfg
- rca/api_content/content.py
- rca/home/models.py
- rca/project_styleguide/templates/patterns/organisms/news/news_api_content.html
- rca/project_styleguide/templates/patterns/pages/home/home_page.html
- rca/settings/base.py
- rca/static_src/sass/components/_section.scss
This is rebased because it was a very old feature.
Updates to the homepage api content feed:
> Adds content feed via api to the homepage (rebased)

- rca/programmes/migrations/0051_update_revisions.py
We made some changes to programme types a while back which saw us delete all the existing taxonomy items, this has caused errors when viewing page revisions with dangling taxonomy links. 
This PR has a migration to update all the page revisions to have programme_type values
> Update revisions missing programme_type as it's causing viewing errors

- rca/api_content/content.py
- rca/project_styleguide/templates/patterns/pages/home/home_page.html
- rca/settings/base.py
- rca/utils/cache.py
If the verdant site we pull content from over the api is down, we should handle the timeout because heroku will crash at 30 seconds
> Limit requests to the legacy site to stop the app crashing

- vagrant/provision.sh
While provisioning the vagrant vm I hit an error with Postgres not starting. This can be fixed by explicitly starting Postgres.
I've also updated Postgres to version 12 to avoid version mismatches.
> Update vagrant Postgres

- Vagrantfile
This should fix an error that occurs due to missing linux kernel headers when you provision the vagrant vm.
> Add workaround for missing linux headers in vagrant

- rca/settings/base.py
- rca/wagtailapi/api.py
- rca/wagtailapi/views.py
- requirements.txt
This should allow us to utlise the custom tag model functionality that was added in this version:
https://docs.wagtail.io/en/v2.9/reference/pages/model_recipes.html#custom-tag-models
> [456] Upgrade Wagtail to 2.9

- rca/programmes/models.py
- rca/shortcourses/models.py
- rca/static_src/javascript/programmes/components/ProgrammesCategories/CategoriesPanels.js
- rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
- rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammeTeaser.js
- rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammeTeaser.test.js
- rca/static_src/javascript/programmes/components/ProgrammesResults/ProgrammesResults.js
- rca/static_src/javascript/programmes/programmes.api.js
- rca/static_src/javascript/programmes/programmes.slice.js
- rca/static_src/javascript/programmes/programmes.types.js
See [tickets/286](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/286) for the initial brief and testing steps. This adds instances of `shortcourses.ShortCoursePage` to the programmes’ listing view, which was so far only displaying instances of `programmes.ProgrammePage`.
This is implemented by doing two separate API calls in parallel, to reduce customisations on the Wagtail API side, after discussion with Kevin and [on Slack](https://torchbox.slack.com/archives/C03R0FNK7/p1589289353027100).
---
I slightly refactored the API field definitions so it’s a bit clearer they are meant to match (not a dealbreaker if they stop matching in the future, as long as it’s intentional, but for now they’re meant to match). The API client makes the two queries in parallel, flattens the …
> 286 Add short courses to the programmes listing API and results views

- rca/landingpages/models.py
- rca/project_styleguide/templates/patterns/molecules/card/card--project.html
- rca/projects/models.py
For [ticket 1106](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1106)
Adds new property `is_startup_project` to _ProjectPage_, which can then be referenced by templates, context processors etc. to determine whether to output the _Start-up_ subtitle instead of the school.
> Add 'Start-up' subtitle to appropriate projects on landing & project picker pages

- rca/api_content/content.py
- rca/project_styleguide/templates/patterns/molecules/card/card_api_content.html
For [ticket 1138](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1138)
This complements [the change](https://github.com/torchbox/verdant-rca/pull/298) on the verdant site to include ongoing events in listings (for [ticket 1072](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1072)).
> News & events API feed on new pages > update to events (part 2)

- rca/project_styleguide/templates/patterns/pages/staff/staff_detail.html
For [ticket 1134](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1134)
This was originally overriding the `title_prefix` block with the staff member's name, but the _base.html_ template was outputting the page's title in the `title` block. This led to double title output.
> Remove duplication in staff profile page title

- rca/home/migrations/0002_create_homepage.py
- rca/programmes/models.py
- rca/settings/base.py
- rca/shortcourses/tests/test_models.py
- rca/utils/blocks.py
- requirements.txt
Upgrade Wagtail to version 2.11.2 as part of the lights-on support for the site.
One test assertion was commented that had failed before the upgrade. I have added a TODO comment for further investigation. 
I have checked the [Wagtail 2.11 upgrade considerations](https://docs.wagtail.io/en/stable/releases/2.11.html#upgrade-considerations) and made changes where necessary (in particular new import location for `SiteMiddleware`).
> Feature/upgrade wagtail 2.11

- rca/schools/models.py
So publishing can begin once we deploy the work... and so that we can preview the new pages, this PR adds a 404 response set on the schools serve method depending on the user.
All is_staff users should be able to see the new schools pages for publishing purposes, but the public should receive a 404 and be rerouted to the old site accordingly until the pages are ready. Eventually, when ready,  we'll remove the custom serve method altogether.
> Allow new school pages to be viewable by is_staff for publishing

- requirements.txt
Fixes CVE-2021-32052 & CVE-2021-31542
https://docs.djangoproject.com/en/3.1/releases/3.1.10/
https://docs.djangoproject.com/en/3.1/releases/3.1.9/
> Update Django to fix CVE-2021-32052 & CVE-2021-31542

- rca/settings/base.py
- rca/utils/embed_finders.py
- rca/utils/tests/test_embed_finders.py
Ticket: https://projects.torchbox.com/projects/rca-website-rebuild/tickets/731
The added tests for the fix passes fine although I haven't been able to manually test on my local build due to this error:
`django.db.utils.IntegrityError: null value in column "hash" of relation "wagtailembeds_embed" violates not-null constraint`
More info on that error here https://github.com/wagtail/wagtail/issues/6764. 
Not sure if that's a problem with data pulled from develop but feel like this should be tackled in a seperate ticket for time constraints.
> 731 Add CustomEmbedFinder to fix title attribute

- rca/static_src/sass/layout/_header.scss
Ticket [1316](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1216).
Currently deploying to [dev](https://rca-development.herokuapp.com/).
Removes `cursor: pointer` on menu/search buttons when they're already active.
> [1316] Remove pointer on active menu items

- rca/static_src/sass/components/_nav.scss
Ticket [1215](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1215).
Currently deploying to [dev](https://rca-development.herokuapp.com/).
Fix horizontal alignment between the first and subsequent navigation lists. Agreed with nl to do away with using the `$gutter` variable here as it no longer serves its purpose.
Before:
After:
Prevent longer menu items from reaching grid line/edge of element (subtle one).
Before:
After:
> Align first and second navigation lists correctly

- rca/project_styleguide/templates/patterns/base.html
- rca/static_src/javascript/components/video-modal.js
- rca/static_src/sass/components/_app.scss
Ticket [1193](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1193).
Currently deploying to [dev](https://rca-development.herokuapp.com/).
Toggles header (via z-index) when modals are open in order to make the close button visible. At present, the header obscures the close button (see prod).
> [1193] Allow modal close button to remain visible by hiding header

- rca/programmes/models.py
- rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
- rca/project_styleguide/templates/patterns/molecules/key-details/key-details.yaml
Implements: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1204
Adds the first item in the list of related schools and research centres to the programme page.
> [1204] add school to programme page

- rca/people/models.py
- rca/users/models.py
- rca/users/templates/wagtailusers/users/list.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1208
This was a lot simpler than I thought it would be. Initially I overode the URLs and views for the user listing, and then found I was only changing anything in the listing template anyway. 
It is not particularly performant to query the groups per user but I couldn't work out an easy way to improve this.
> Add groups to admin user listing

- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--dev-all-fields.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.yaml
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.yaml
Removing aria as it was causing AXE errors when the text was totally different to the editor's label. 
We originally did this as all links were "Read more", however, editors have now been educated to use more descriptive labelling, meaning the aria is no longer required.
> Removing aria and “read more” link option

- rca/utils/wagtail_hooks.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1142
Uses the existing template code function to check if 'external' link provided in rich text content is actually an RCA (eg legacy site) url, and does not add target attribute if so.
> 1142 - If external link is legacy site, do not open in new tab

- rca/static_src/sass/components/_form-item.scss
Removing the content added state of forms as it didn't meet WCAG 2.1 contrast requirements
> Removing style on form when content is added - lack of contrast

- rca/static_src/sass/components/_search.scss
Updating global search focus state
Ticket:
projects.torchbox.com/projects/rca-website-rebuild/tickets/1000
Staging:
rca-development.herokuapp.com/
<details>
<summary>Screenshots + </summary>
</details>
> Adding orange focus state to global search

- rca/project_styleguide/templates/patterns/molecules/filter-tab-options/filter-tab-options.html
- rca/project_styleguide/templates/patterns/pages/scholarships/scholarships_listing_page.html
- rca/static_src/javascript/components/project-filters.js
Javascript to allow us to specify that only one filter should be selectable - the form should submit when a filter item is chosen.
> Add functionality to only have a single filter option in filter takeover

- rca/static_src/sass/layout/_footer.scss
Small tweak to ensure when more than 3 items are added to the footer that they wrap:
> Making 4th+ footer link wrap onto new line

- rca/static_src/sass/components/_share-item.scss
Adding left padding to social items so they no longer butt up against images in the main content column:
Example URL: https://rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/editorial/editorial_detail.html
Ticket URL: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2418
Before:
After:
> Adding left space to large breakpoint social items

- rca/api_content/content.py
Ticket [656](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/656)
The get request for the social image should go through the custom `fetch` method since it passes through the catching pattern. At the moment it's not, which is resulting in [ReadTimeout](https://sentry.io/organizations/torchbox/issues/?environment=production&project=1542908&query=is%3Aunresolved&statsPeriod=24h) exceptions being raised.
This will mean `CantPullFromRcaApi` will be raised, ideally, I'd like to completely silence this logging with the `settings.API_FETCH_LOGGING` env var I set up (the legacy site isn't very responsive to the requests) but they are still occasionally being logged in sentry
> Stop logging everything

- rca/project_styleguide/templates/patterns/pages/project/project_listing.html
- rca/project_styleguide/templates/patterns/pages/staff/staff_index.html
- rca/project_styleguide/templates/patterns/pages/student/student_index.html
Making the results text a heading
Ticket:
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2207
Staging:
rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/events/event_listing.html#
> Making results title a h2 on listing pages

- rca/editorial/models.py
- rca/events/models.py
Ticket [2420](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2420)
Resolves sentry error: https://sentry.io/organizations/torchbox/issues/3410762474/?environment=production&project=1542908&query=is%3Aunresolved
> #2420 page__live isn't a supported QS filter

- rca/events/filter.py
This PR adjusts the QS for events to include events that are in progress.
Before this, we where filtering for events that start date was greater than or equal to today, what we want is an end_date that is greater than or equal to today; this will include events in the listing that are 1st to 8th of December (if today is the 5th)
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2466
<details>
</details>
<details>
</details>
> #2466 Reorder events to include those in progress

- poetry.lock
- pyproject.toml
- rca/enquire_to_study/wagtail_hooks.py
- rca/settings/base.py
This PR adds a [date range](https://github.com/wunderweiss/wagtail-rangefilter) filter to the enquire to study export. 
This is needed as heroku has a 30s response limit which is timing out when larger data sets are exported. With this filter, the administrator can create exports within a specific timeframe meaning the data will be smaller and will be within the 30s threshold.
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2448
<details>
<summary>Screenshots</summary>
</details>
> #2448 Adds date filter to data export for granular reports

- rca/events/models.py
- rca/guides/models.py
- rca/project_styleguide/templates/patterns/organisms/index-module/index-module.html
This PR makes a few changes to summary and introduction values.
We are only addressing Guides and Evens in this PR, we may want to revisit other areas we choose an introduction or summary to show. It's a bit more work if we start addressing other areas as they are formatted in different ways, so for now we are just addressing what's been raised on the ticket.
Link to test page: http://0.0.0.0:8000/research-innovation/research-centres/helen-hamlyn-centre/include-2022-submissions/
<details>
<summary>Before: </summary>
</details>
<details>
<summary>After: </summary>
</details>
> #2476 Fixes bad rendering of summary values

- rca/editorial/models.py
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2439
This PR updates the priority in which field to use for the related pages section.
Screenshot (ignore the images):
> #2439 - BE - Listing summary field not being used on news items

- rca/events/models.py
- rca/events/tests/test_models.py
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2437
This PR removes the validation for the `end_time` when creating or editing an event detail page. I've confirmed that removing the validation won't break importing the page to the intranet.
Screenshot:
Left is the one from RCA website and right is the one from the intranet after running the import.
> #2437 - BE Event items: support events with no end time

- rca/account_management/tests/test_admin.py
Ensure the search bar is still visible for editor roles, not just `admin`
> Add tests for admin UI

- rca/static_src/sass/abstracts/_variables.scss
- rca/static_src/sass/base/_typography.scss
RCA uses a different font to style bold items (due to font licensing limitations), this hadn't been applied to the b tag so items within a b looked fuzzy, this MR rectifies this.
> Styling b tag to use correct font

- rca/project_styleguide/templates/patterns/molecules/people-carousel/people-carousel.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel--quotes.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel--square.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel_api_content.html
- rca/project_styleguide/templates/patterns/organisms/logo-carousel/logo-carousel.html
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2489
Issue: The carousel is displayed inside a form (for filtering). When a user clicks on a carousel arrow, the form shouldn't be submitted.
> #2489 - SPIKE News index jumps when scrolling through Editorial picks carousel

- rca/landingpages/models.py
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--tap.html
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2483
This PR adds the TAP widget field to landing pages. It looks like landing pages already had the field since they already inherit from `LandingPage` - it just wasn't added to the content panels.
> #2483 - Add TAP Widget to additional page types

- rca/project_styleguide/templates/patterns/organisms/news/news_api_content.html
- rca/project_styleguide/templates/patterns/pages/editorial_event_landing/editorial_event_landing.html
Ticket: [here](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2494)
Hi, 
this is a simple fix to passthrough the correct button title from the EELandingPage model, it was passing througt the news button title instead of the event. I've just made it a little more flexible to allow for this.
Image of fixed page: 
Thanks - Will.
> Alllow passing button title to news_api_content template

- rca/project_styleguide/templates/patterns/molecules/image-caption-link/image-caption-link.html
- rca/project_styleguide/templates/patterns/organisms/image-video-block/image-video-block.html
- rca/project_styleguide/templates/patterns/organisms/programme_tabs/apply.html
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2505)
When a _curriculum image_ or _apply image_ is not specified on a Programme page, we expect that the image should not be rendered at all. However, what happens is that the image block is displayed with a null URL. This PR fixes this by checking that the images exist before proceeding to render them.
<details>
<summary>Here is an illustration</summary>
https://github.com/torchbox/rca-wagtail-2019/assets/7713776/feaccdcb-ffb0-4986-b0f6-55aa95af9a54
</details>
> #2505 | Fix: Conditional rendering of images on Requirements and Apply tab optional

- rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2504)
This PR modifies the display of programme page key details so that the link to open days is rendered even when next open day date is not specified.
<details>
</details>
<details>
</details>
> #2504 » Programme page > Key details > Enable Open Day link to show up without Open Day date

- rca/project_styleguide/templates/patterns/molecules/anchor-nav/anchor-nav.html
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2516)
This PR changes the `anchor-nav` heading text to match that of the `jump-nav`.
<details>
</details>
<details>
</details>
> #2516 » Guide page > 'On this page' side menu > change heading

- rca/project_styleguide/templates/patterns/molecules/anchor-nav/anchor-nav.html
Reverts torchbox/rca-wagtail-2019#953
because this was accidentally merged in
> Revert "#2516 » Guide page > 'On this page' side menu > change heading"

- rca/project_styleguide/templates/patterns/molecules/key-details/key-details--schools.html
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2518)
This PR modifies the display of school page key details so that the link to open days is rendered even when next open day date is not specified.
>**Note**
>
> This is similar to #951, which does the same thing but on programme pages. 
<details>
</details>
<details>
</details>
> #2518 » School page > Key details > Enable Open Day link to show up without Open Day date

- rca/programmes/models.py
- rca/shortcourses/models.py
- rca/static_src/javascript/components/programme-toggle-switch.js
- rca/static_src/javascript/main.entry.js
- rca/static_src/javascript/programmes/components/ProgrammesExplorer.js
- rca/static_src/javascript/programmes/components/StudyModeToggleSwitch.js
- rca/static_src/javascript/programmes/programmes.api.js
- rca/static_src/javascript/programmes/programmes.api.test.js
- rca/wagtailapi/filters.py
- rca/wagtailapi/views.py
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2509)
This is to allow users to filter programmes by study mode.
Changes made:
- added a new BaseFilterBackend which checks for 'part-time'  in the API GET query params, then filters the queryset accordingly (d6edbb73)
- added a `StudyModeToggleSwitch` React component (8920b594)
- added logic to handle events on the toggle switch  (b7aa3f49)
- updated the frontend API logic to include filtering results by part-time (0f636413)
<details>
<summary>Illustration</summary>
https://github.com/torchbox/rca-wagtail-2019/assets/7713776/d0cc5936-a196-4fb1-8a5e-af8758804537
</details>
>**Warning**
>
> - ~~The JS test suite is broken, needs fixing, @nicklee would you please take a look?~~ fixed in b539acdc
> - The toggle …
> #2509 BE Programme finder > Add study mode filter

- rca/programmes/models.py
- rca/programmes/utils.py
- rca/utils/models.py
This PR fixes the indexing of the content of Accordion Snippets.
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2524)
Because Accordion Snippets are used on Pages via a SnippetChooserBlock in a StreamField, their content isn't actually part of the StreamField itself. Therefore, searching a Page for values within the Snippets yielded no results.
Attempting to use `index.RelatedFields` will also not work, because there's no relationship between the Page and the `AccordionSnippet`. Therefore, the solution is to write custom functions and index those functions, as indicated in the [Wagtail docs](https://docs.wagtail.org/en/stable/topics/search/indexing.html#indexing-callables-and-other-attributes).
Even though it was not required in this ticket, I have also …
> № 2524 - Site search > Crawling accordion content

- rca/enquire_to_study/tests/test_views.py
- rca/enquire_to_study/views.py
- rca/project_styleguide/templates/patterns/emails/enquire_to_study.txt
- rca/settings/base.py
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2526
This MR adds the feature of sending an internal email to specified email addresses when a user answers the enquire to study form.
> #2526 - Enquire to study form

- rca/account_management/tests/test_forms.py
- rca/account_management/views.py
- rca/settings/base.py
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2528)
This PR adjusts the password reset timeout to give more time for students to reset their passwords. 
Because `PASSWORD_RESET_TIMEOUT_DAYS` is [deprecated in Django 3.1](https://docs.djangoproject.com/en/3.2/ref/settings/#password-reset-timeout-days), we now use `PASSWORD_RESET_TIMEOUT` instead.
> № 2528 | Research Student Accounts > Take off time limit on passwords

- rca/project_styleguide/templates/patterns/molecules/hero/hero--home.html
- rca/static_src/sass/components/_hero.scss
[ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2531)
On mobile devices, the hero image cropping doesn't respect the focal point defined on the image in Wagtail Admin. This PR attempts to fix this by adjusting the size of the image being cropped, so that we are cropping the correct region.
<details>
<summary>Image focal point</summary>
</details>
<details>
</details>
<details>
</details>
> № 2531 - SPIKE Image focal point selector

- rca/events/factories.py
- rca/events/models.py
- rca/events/tests/test_models.py
There was a [bug](https://torchbox.monday.com/boards/1318157635/pulses/1319720954/posts/163028834) reported that events were not showing in the events index, on inspection this looks like some end dates have been published before the start date, by accident. So this should ensure that is no longer possible.
> Makes time travel impossible to publish

- rca/enquire_to_study/views.py
[Ticket reference](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2547#update-73443141)
While testing #985, it was observed that the internal emails showed programmes without the degree level. This is a small fix to rectify this.
<details><summary>Here's what the emails now look like</summary>
[![Screenshot](https://github.com/torchbox/rca-wagtail-2019/assets/7713776/5fa74f64-f278-4fd6-93a1-f5b33f3f9ed2)](https://github.com/torchbox/rca-wagtail-2019/assets/7713776/5fa74f64-f278-4fd6-93a1-f5b33f3f9ed2)
</details>
> № 2547 » BE | Add degree level to programmes in the internal email body

- rca/project_styleguide/templates/patterns/molecules/tab-nav/tab-nav.html
- rca/static_src/sass/components/_tab-item.scss
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2543
This PR updates the color of the Apply button found in programme pages. They should be orange all the time.
Screenshot:
> #2543 - Programme page > Sticky jump menu > Apply button

- rca/project_styleguide/templates/patterns/pages/editorial/editorial_detail.html
- rca/project_styleguide/templates/patterns/pages/guide/guide.html
- rca/static_src/sass/components/_booking-bar.scss
- rca/static_src/sass/components/_section.scss
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2540
This PR fixes an issue where the CTA is cut when it's at the very bottom of the page and that there is no hero image. This doesn't happen all the time though so I've checked pages which uses the `contact.html`.
Screenshots using the provided links in the ticket:
> #2540 - FE | Site-wide > Large CTAs > Bug affecting display

- rca/project_styleguide/templates/patterns/molecules/search-result/search-result.html
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2550
This PR updates how the search description is displayed. Since we're using `firstof`, special characters are displayed as different characters.
> #2550 - SPIKE | Special characters not rendering in listing summary

- rca/project_styleguide/templates/patterns/molecules/people-carousel/people-carousel.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel--quotes.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel--square.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel.html
- rca/project_styleguide/templates/patterns/organisms/carousel/carousel_api_content.html
- rca/project_styleguide/templates/patterns/organisms/logo-carousel/logo-carousel.html
- rca/static_src/sass/components/_carousel.scss
- rca/static_src/sass/components/_slideshow.scss
Ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2539
This PR updates the mobile view of carousels/slideshows throughout the build. Previously, it wasn't obvious that users could scroll through the component on mobile/tablet view. We then add the arrows instead to help users know about that.
Screenshots:
> #2539 - SPIKE FE Image gallery on mobile view

- docs/upgrading.md
- rca/people/templates/admin/panels/student_page_inline_panel.html
- rca/people/templates/admin/panels/student_page_inline_panel_child.html
- rca/people/utils.py
[Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2554)
Hiding the `StudentPageInlinePanel` contents resulted in the following error when the child elements had content, and a non-superuser attempted to save changes to the Page, or preview it:
<details><summary>Traceback</summary>
```console
KeyError: 'related_schools-0-id'
File "django/utils/datastructures.py", line 84, in __getitem__
list_ = super().__getitem__(key)
MultiValueDictKeyError: 'related_schools-0-id'
File "django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "django/views/decorators/cache.py", line 62, in _wrapper_view_func …
```
> № 2554 | Make Related Research Centres and Related Schools read only for Research Students

- rca/enquire_to_study/forms.py
[ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2553)
This PR makes some small modifications to the `city` field in the `EnquireToStudyForm`. These are meant to help with getting more consistent input from respondents, and are as follows
- impose a character limit of 20
- [disable browser autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#sect2)
- add help text modelling the answer the client would like them to input
<details><summary>Screenshot</summary>
</details>
> №2553 | Register your interest form » City of Residence Field

- rca/project_styleguide/templates/patterns/organisms/image-video-block/image-video-block.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--innovation.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--tap.html
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1472503830
This PR fixes an issue where the link text is not being passed to the image video block. We'll need to update multiple templates as there are multiple pages that uses this `featured_image`.
> #3830 - Accessibility: Landing Page > Featured content module > Link text

- rca/editorial/models.py
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1472503879
This PR fixes an issue where duplicate results are shown when doing multiple filters in the editorial listing page. It's a simple fix!
> #3879 - Listing pages: duplicates appearing in results

- rca/project_styleguide/templates/patterns/molecules/card/card.html
- rca/project_styleguide/templates/patterns/molecules/card/card_api_content.html
- rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
- rca/project_styleguide/templates/patterns/molecules/profile-detail/profile-detail.html
- rca/project_styleguide/templates/patterns/organisms/index-module/index-module.html
- rca/project_styleguide/templates/patterns/pages/guide/guide.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--enterprise.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--generic.html
- rca/project_styleguide/templates/patterns/pages/landingpage/landing_page--research.html
- rca/project_styleguide/templates/patterns/pages/project/project_detail.html
- rca/project_styleguide/templates/patterns/pages/researchcentre/research_centre.html
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1494025078
This PR fixes "content heading" issues found by Siteimprove. Using the list provided in the ticket, I've checked the pages using the Chrome extension.
There are some that are content managed issues (editors entering 2 h3s in a row in a rich text) so we couldn't do anything about those.
> #5078 - Accessibility: Content missing after heading

- rca/project_styleguide/templates/patterns/atoms/link-primary/link-primary--download.html
- rca/project_styleguide/templates/patterns/atoms/link-secondary/link-secondary--download.html
- rca/project_styleguide/templates/patterns/atoms/link-tertiary/link-tertiary--download.html
- rca/project_styleguide/templates/patterns/molecules/key-details/key-details--project.html
- rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1472503836
This ticket covers adding both the file type and file size when displaying document uploads.
> #3836 - Accessibility: STAS-A01: Links to Non-HTML Documents (open in a new tab/window) pg 69

- rca/static_src/sass/abstracts/_variables.scss
- rca/static_src/sass/components/_audience-nav-item.scss
- rca/static_src/sass/components/_body.scss
- rca/static_src/sass/components/_breadcrumb.scss
- rca/static_src/sass/components/_burger.scss
- rca/static_src/sass/components/_card.scss
- rca/static_src/sass/components/_categories-tablist.scss
- rca/static_src/sass/components/_donate-form.scss
- rca/static_src/sass/components/_facilities.scss
- rca/static_src/sass/components/_featured-alumni.scss
- rca/static_src/sass/components/_footer-link-item.scss
- rca/static_src/sass/components/_form-item.scss
- rca/static_src/sass/components/_hero-action-pane.scss
- rca/static_src/sass/components/_jump-nav.scss
- rca/static_src/sass/components/_key-details.scss
- rca/static_src/sass/components/_link.scss
- rca/static_src/sass/components/_logo-card.scss
- rca/static_src/sass/components/_nav.scss
- rca/static_src/sass/components/_overview.scss
- rca/static_src/sass/components/_profile-detail.scss
- rca/static_src/sass/components/_programme-teaser.scss
- rca/static_src/sass/components/_rich-text.scss
- rca/static_src/sass/components/_scroll.scss
- rca/static_src/sass/components/_search-toggle.scss
- rca/static_src/sass/components/_skip-link.scss
- rca/static_src/sass/components/_slide.scss
- rca/static_src/sass/components/_step-item.scss
- rca/static_src/sass/components/_tab-item.scss
- rca/static_src/sass/layout/_footer.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1472503766
This PR updates all xxxs, xxs, and xs font sizes to 18px. We also remove some `font-size: map-get($large-font-sizes, xxs);` as they're all now 18px.
> #3766 - Accessibiity: Design System & Colour Contrast

- rca/static_src/sass/components/_hero-action-pane.scss
- rca/static_src/sass/layout/_header.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1472503766/posts/277421268
This PR fixes an issue with misaligned items due to the font size changes.
> #1268  -Accessibiity: Design System & Colour Contrast

- rca/reports/tests/test_reports.py
- rca/reports/views.py
- rca/reports/wagtail_hooks.py
- rca/settings/base.py
Ticket: https://torchbox.monday.com/boards/1472452416/views/14036164/pulses/1509657048
> 7048: Include page URLs in exported aging pages reports

- rca/project_styleguide/templates/patterns/molecules/relatedcontent/relatedprogrammes.html
- rca/shortcourses/models.py
[Ticket](https://torchbox.monday.com/boards/1472452416/pulses/1472503761)
> [!NOTE]  
> This change should only be applicable for **related short courses**
Example used:
`study/programme-finder/progression-portfolio-development/`
> #3761 - Related page lists showing short courses

- rca/users/templates/wagtailusers/users/list.html
This is a small fix on the display of the overriden `wagtail/users/templates/wagtailusers/users/list.html` template. Please see the details below:
<details>
</details>
<details>
</details>
> [!NOTE]
> It's worth noting that the `wagtail/users/templates/wagtailusers/users/list.html`  template is [removed in Wagtail 6.1](https://github.com/wagtail/wagtail/commit/7b1644eb37b6b6cf7800276acf9abef5254fc096). This is therefore a temporary fix before we upgrade to Wagtail 6.1
> Fix broken wagtailadmin user listing

- rca/project_styleguide/templates/patterns/pages/shortcourses/short_course.html
- rca/static_src/sass/components/_page.scss
The text within the booking bar often sits on one line. For example: https://www.rca.ac.uk/study/programme-finder/service-design-masterclass/
However, when the label is 'Register your interest for upcoming dates', it flows onto two lines. The page layout breaks when this happens, as heights/margins/etc assume the booking bar is shallower. For example, see the whitespace below the hero here: https://www.rca.ac.uk/study/programme-finder/human-centred-design-for-intelligent-mobility/
This PR aims to fix that. Creating a new modifier seemed like the easiest way, and we want to fix this asap since it's an issue on prod.
> Fix broken layout on short course pages

- rca/project_styleguide/templates/patterns/molecules/streamfield/blocks/table_block.html
- rca/static_src/javascript/components/table-hint.js
- rca/static_src/javascript/main.entry.js
- rca/static_src/sass/components/_table.scss
- rca/static_src/sass/main.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1538457446
Adds FE for the typed table block including a hint that shows under 600px so the user knows they can scroll the table horizontally to see all the content. 
Desktop screen:
<details><summary>Details</summary>
</details> 
Mobile video:
<details><summary>Details</summary>
https://github.com/user-attachments/assets/af31a75e-aea9-49bb-a97f-591a4c9f7f48
</details> 
Note that the original work for this MR (https://github.com/torchbox/rca-wagtail-2019/pull/1021) was merged to dev so i've had to follow suit.
> [7446] Typed Table Block FE

- rca/static_src/sass/components/streamfield.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1472503877
There was no space above non-anchor headings on the guide pages so they looked odd in comparison to the anchor headings. This MR fixes that.
<details><summary>Before:</summary>
<p>
</p>
</details> 
<details><summary>After:</summary>
<p>
</p>
</details>
> [3877] Non-anchor headings on guide page spacing

- rca/static_src/sass/components/_table.scss
[Ticket](https://torchbox.monday.com/boards/1472452416/pulses/1538457446)
Missing commit for master - removing typed table block and left-aligning caption
> 7446 - typed table block caption alignment and borders

- rca/project_styleguide/templates/patterns/pages/guide/guide.html
- rca/static_src/sass/abstracts/_variables.scss
- rca/static_src/sass/components/_app.scss
- rca/static_src/sass/components/_grid.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1538412601
FE fixes for the shorthand embed that can be added to a guide page:
- Add a body class to the guide page when a shorthand embed has been added to the page
- Hide the grid lines on the guide page when the embed is on the page
- Make sure the header, search and nav appear on top of the embed
> [2601] Shorthand Embed FE

- rca/static_src/sass/components/_carousel.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1617104730
This MR fixes an issue where the arrows buttons for a carousel might sometimes be unclickable. It's because they're hidden behind another element.
> #4730 - BUG | Guide Page > Related Staff module (desktop)

- rca/static_src/sass/components/_hero-action-pane.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1630887888
This PR fixes an issue where the hero CTA sub text is cut off on mobile.
Screenshot:
> #7888 - BUG | Home 'Hero CTA sub text'

- rca/project_styleguide/templates/patterns/pages/shortcourses/short_course.html
- rca/static_src/sass/components/_booking-bar.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1559054453
This PR fixes a white bar issue for short course pages.
Screenshot:
> #4453 - BUG | FE | Programme page whitespace

- rca/project_styleguide/templates/patterns/atoms/back-link/back-link.html
- rca/project_styleguide/templates/patterns/molecules/video-modal/video-modal.html
- rca/static_src/sass/components/_back-link.scss
- rca/static_src/sass/components/_video-modal.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1663117265
This PR makes some accessibility fixes to some elements in the build:
- In the navigation, 'Back' is set to as a link which is not focusable. We update this to be a button.
- When opening a video embed, the close button is not focusable as well. We update this to be a button.
In the ticket/document, there's a link in https://www.rca.ac.uk/study/programme-finder/art-design-graduate-diploma/ which is not focusable -- specifically the one with the text "Next on-campus open day: 16 October 2024". This is caused by a broken link so that just needs to be updated editorially.
> #7265 - Accessibility | ADR_21184-5 Anchor tags with no href do not receive keyboard focus

- docs/integrations.md
- docs/support-runbook.md
- docs/upgrading.md
- poetry.lock
- pyproject.toml
- rca/account_management/views.py
- rca/project_styleguide/templates/patterns/pages/auth/login.html
- rca/project_styleguide/templates/patterns/pages/auth/logout_confirmation.html
- rca/settings/base.py
- rca/urls.py
- rca/utils/pipeline.py
Ticket: https://torchbox.monday.com/boards/1472452416/views/14036164/pulses/1582473718
This PR adds SSO to the RCA site. Users can then log in via SSO - if they have a Microsoft AD account.
Additional features:
1. Users who logs in via SSO are automatically added as an "Editor".
2. Users who logs in via SSO will see a logout confirmation page when they logout from the Wagtail admin.
> #3718 - Implement SSO for rca.ac.uk

- rca/project_styleguide/templates/patterns/molecules/key-details/key-details.html
This ticket covers updating the label of the key details in program pages to be "Current location" instead of just "Location".
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1745180965
No BE changes for this.
> #0965 - PROGRAMME PAGES - KEY DETAILS | Change field label 'Location' to 'Current Location'

- rca/projects/models.py
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1667565931
This MR updates the listing order of research projects. It used to be that its only sorted by title. We want to use the end date instead.
> #5931 - Listing order of research projects

- rca/project_styleguide/templates/patterns/molecules/hero-action-pane/hero-action-pane.html
- rca/project_styleguide/templates/patterns/pages/home/home_page.html
- rca/static_src/sass/components/_hero-action-pane.scss
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1636969177
This PR refactors the CTA section in the hero home page. The gist of the changes are:
- Move the hero action pane away from the main content area to below the hero image.
- On desktop, pull the hero action pane up.
> #9177 - FE | Home hero text component refactor

- rca/utils/forms.py
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1605295479
This MR makes the three fields required:
1. Social networks (image)
2. Social text
3. Listing information image
> #5479 - GUIDE, EDITORIAL, EVENT TEMPLATES | Add extra required fields

- rca/utils/models.py
As the legacy site is no longer online, calls to its content from the `refetch_legacy_news_and_events` fail, causing errors on pages whose templates render the legacy content. This fixes those errors by making `refetch_legacy_news_and_events` return an empty list instead, which will get things working until a longer-term code cleanup can take place.
> Stop pulling news & events from the defunct legacy site

- rca/project_styleguide/templates/patterns/molecules/key-details/key-details--schools.html
- rca/schools/models.py
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1811011007
This PR updates the hard coded 'Location' label on school pages.
> #1007 - SCHOOLS  PAGES - KEY DETAILS | Change field label 'Location' to 'Current Location'

- rca/projects/models.py
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1811016855
This PR updates the ordering of projects in the project picker page. Previously, it's based on end date with the ones with no end date being first. Instead, it'll just be based on when it was first published (so newer ones are surfaced).
> #6855 - BUSINESS | Case Studies Listing order

- rca/home/models.py
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1808782535
This PR updates the meta label in featured alumni section in the home page to use the types of the editorial page. Currently, it's all hard coded to "Alumni stories".
> #2535 - FE | Home page - Featured Alumni stories logic

- rca/project_styleguide/templates/patterns/atoms/link-primary/link-primary--external.html
- rca/project_styleguide/templates/patterns/molecules/key-details/key-details--staff.html
Ticket: https://torchbox.monday.com/boards/1472452416/pulses/1781140078
This PR adds an option for external links to be opened in a new URL. This is used in the research profile URL of staff pages.
> #0078 - BE + FE | Staff Profiles add research profile CTA button

- rca/project_styleguide/templates/patterns/organisms/image-video-block/image-video-block.html
- rca/project_styleguide/templates/patterns/organisms/image-video-embed/image-video-embed.html
- rca/project_styleguide/templates/patterns/organisms/image-video-embed/image-video-embed.yaml
- rca/project_styleguide/templates/patterns/organisms/programme_tabs/programme_overview.html
- rca/static_src/sass/components/_image-video-embed.scss
- rca/static_src/sass/main.scss
This PR restyles the video embed in programme pages. All other pages/areas where a video embed exists are untouched.
Ticket: https://torchbox.atlassian.net/browse/R1-224
<details><summary>Screenshots</summary>
<p>
Default:
On hover:
</p>
</details>
> R1-224: PROGRAMME PAGE | Video display

- docs/upgrading.md
- rca/search/migrations/0001_initial.py
- rca/search/migrations/__init__.py
- rca/search/views.py
- rca/settings/base.py
Closes https://torchbox.atlassian.net/browse/R1-245
`pg_trgm` is enabled via migrations in the search app, so it should be available for all deployment envs. 
The threshold currently is set at 0.1 (as a constant in rca/search/views.py, which is quite forgiving.
> Add trigram similarity search to search view

- rca/editorial/admin_forms.py
Ticket: https://torchbox.atlassian.net/browse/R1-250
This PR makes the fields title tag and meta description in editorial page to be required.
> R1-250: EDITORIAL PAGE | Make Title Tag & Meta Description a required field
